#!/usr/bin/python
# coding: utf-8

from pdfminer.pdfparser import PDFParser, PDFDocument, PDFNoOutlines
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LAParams, LTTextBox, LTTextLine, LTFigure, LTImage, LTTextLineHorizontal
import sys, string, os, math,re 
from binascii import b2a_hex
from operator import itemgetter


def with_pdf (pdf_doc, pdf_pwd, fn, *args):
    """Open the pdf document, and apply the function, returning the results"""
    result = None
    try:
        # open the pdf file
        fp = open(pdf_doc, 'rb')
        # create a parser object associated with the file object
        parser = PDFParser(fp)
        # create a PDFDocument object that stores the document structure
        doc = PDFDocument()
        # connect the parser and document objects
        parser.set_document(doc)
        doc.set_parser(parser)
        # supply the password for initialization
        doc.initialize(pdf_pwd)

        if doc.is_extractable:
            # apply the function and return the result
            result = fn(doc, *args)

        # close the pdf file
        fp.close()
    except IOError:
        # the file doesn't exist or similar problem
        pass
    return result

def _parse_toc (doc):
    """With an open PDFDocument object, get the table of contents (toc) data
    [this is a higher-order function to be passed to with_pdf()]"""
    toc = []
    try:
        outlines = doc.get_outlines()
        for (level,title,dest,a,se) in outlines:
            toc.append( (level, title) )
    except PDFNoOutlines:
        pass
    return toc

def get_toc (pdf_doc, pdf_pwd=''):
    """Return the table of contents (toc), if any, for this pdf file"""
    return with_pdf(pdf_doc, pdf_pwd, _parse_toc)

def _parse_pages (doc, images_folder):
    """With an open PDFDocument object, get the pages, parse each one, and return the entire text
    [this is a higher-order function to be passed to with_pdf()]"""
    rsrcmgr = PDFResourceManager()
    laparams = LAParams()
    device = PDFPageAggregator(rsrcmgr, laparams=laparams)
    interpreter = PDFPageInterpreter(rsrcmgr, device)

    text_content = [] # a list of strings, each representing text collected from each page of the doc
    text_content.append('<pdf2xml>')
    for i, page in enumerate(doc.get_pages()):
        
        interpreter.process_page(page)
        # receive the LTPage object for this page
        layout = device.get_result()
        page_left = int(layout.bbox[0])
        page_top = int(layout.bbox[1])
        page_width = int(layout.bbox[2])
        page_height = int(layout.bbox[3])
        text_content.append('<page l="%s" t="%s" w="%s" h="%s" number="%s">' % (page_left,page_top,page_width,page_height,(i+1)))
        # layout is an LTPage object which may contain child objects like LTTextBox, LTFigure, LTImage, etc.
        ret = parse_lt_objs(layout._objs, (i+1), images_folder, page_height)
        text_content.append(ret)
        text_content.append('</page>')
    text_content.append('</pdf2xml>')
    return text_content

def get_pages (pdf_doc, pdf_pwd='', images_folder='/tmp'):
    """Process each of the pages in this pdf file and print the entire text to stdout"""
    #print '\n\n'.join(with_pdf(pdf_doc, pdf_pwd, _parse_pages, *tuple([images_folder])))
    print '\n'.join(with_pdf(pdf_doc, pdf_pwd, _parse_pages, *tuple([images_folder])))

def parse_lt_objs (lt_objs, page_number, images_folder, page_height, text=[]):
    """Iterate through the list of LT* objects and capture the text or image data contained in each"""
    text_content = []

    page_text = {} # k=(x0, x1) of the bbox, v=list of text strings within that bbox width (physical column)
    for lt_obj in lt_objs:
        if isinstance(lt_obj, LTTextBox) or isinstance(lt_obj, LTTextLine):
            # text, so arrange is logically based on its column width
            update_page_text_hash(page_text, lt_obj)
        elif isinstance(lt_obj, LTImage):
            # an image, so save it to the designated folder, and note it's place in the text
            saved_file = save_image(lt_obj, page_number, images_folder)
            if saved_file:
                # use html style <img /> tag to mark the position of the image within the text
                text_content.append('<img src="'+os.path.join(images_folder, saved_file)+'" />')
            else:
                print >> sys.stderr, "error saving image on page", page_number, lt_obj.__repr__
        elif isinstance(lt_obj, LTFigure):
            # LTFigure objects are containers for other LT* objects, so recurse through the children
            text_content.append(parse_lt_objs(lt_obj._objs, page_number, images_folder, page_height, text_content))

    page_text_items = [(k[0], k[1], k, v) for k,v in page_text.items()]

    page_text_items = list(sorted(sorted(page_text_items, key=itemgetter(0)), key=itemgetter(1), reverse=True))
    sorted_text = [(c,d) for a,b,c,d in page_text_items]
    
    for k, v in sorted_text:
        # sort the page_text hash by the keys (x0,x1 values of the bbox),
        # which produces a top-down, left-to-right sequence of related columns
        a = k
        pos = 'l="%s" t="%s" w="%s" h="%s"' % (int(a[0]), page_height-int(a[3]), int(a[2]-a[0]), int(a[3]-a[1]))
        text_pos = '%s' % (position_fix(int(a[0]),int(a[2]-a[0]),int(a[3]-a[1]),v))
        text_content.append('  <block %s>' % pos)
        text_content.append('    <text %s p="%s">%s</text>' % (pos, text_pos,v))
        text_content.append('  </block>')
    return '\n'.join(text_content)  
    
    

def chinese_count(s):
    r = re.compile('[\x80-\xff]+')
    cLen = 0
    m = r.findall(s)
    for chiness in m:
        cLen = cLen + len(chiness)
    return int(cLen//3)
            
def auto_width(s):
    total_length = len(s)
    cn_length = chinese_count(s)
    less_length = total_length-cn_length*3
    if cn_length==0:
        return total_length
    avl_p =2
    if less_length/cn_length==0:
        avl_p = 2.26
    elif less_length/cn_length<0.3:
        avl_p = 2.24
    elif less_length/cn_length<0.5:
        avl_p = 2.23
    elif less_length/cn_length<0.8:
        avl_p = 2.22
    elif less_length/cn_length<=1:
        avl_p = 2.2
    elif less_length/cn_length>5:
        avl_p = 1.2
    elif less_length/cn_length>4:
        avl_p = 1.4
    elif less_length/cn_length>3:
        avl_p = 1.6
    elif less_length/cn_length>2:
        avl_p = 1.8
    elif less_length/cn_length>1:
        avl_p = 2.18
    width_length = int(avl_p*cn_length+less_length)
    #print(s+"-->total_length:"+str(total_length)+'\n'+"-->cn_length:"+str(cn_length)+'\n'+"-->width_length:"+str(width_length)+'--------------------\n')
    return width_length
    
def position_fix(left,width,height,strp):
    ustrp = unicode(strp, "utf-8")
    strp2 = strp.replace('     ','\n\n\n\n\n\n').replace(' 　　','\n\n\n\n').replace('　　','\n\n\n').replace('　','\n\n').replace(' ','\n')
    strings = strp2.split('\n')
    if len(strings)<=1:
        return str(left)+','+str(width)
    else:
        text_p_dot = ''
        string_width = auto_width(strp)
        per_word_width = int(width//string_width)
        p_left = left
        width_left = 0
        width_per= 0
        for i in range(len(strings)):
            width_left = p_left+width_per
            width_per = int(per_word_width*max(1.2,auto_width(strings[i])))
            if i==0:
                text_p_dot = str(p_left)+','+str(width_per)
            else:
                if strings[i]=='':
                    p_left = width_left+per_word_width
                    #text_p_dot = text_p_dot+'@'+str(p_left)+'&'
                else:
                    p_left = width_left+per_word_width
                    p_dot =str(p_left)+','+str(width_per)
                    if width_per:
                        text_p_dot = text_p_dot+','+p_dot
    return str(text_p_dot)


def to_bytestring (s, enc='utf-8'):
    """Convert the given unicode string to a bytestring, using the standard encoding,
    unless it's already a bytestring"""
    if s:
        if isinstance(s, str):
            return s
        else:
            return s.encode(enc)

def update_page_text_hash (h, lt_obj, pct=0.2):
    """Use the bbox x0,x1 values within pct% to produce lists of associated text within the hash"""
    #a = lt_obj.bbox
    #print 'left="%s" top="%s" width="%s" height="%s"' % (int(a[0]), int(a[1]), int(a[2]-a[0]), int(a[3]-a[1]))
    for obj in lt_obj._objs:
        if isinstance(obj, LTTextLineHorizontal):
            h[obj.bbox] = to_bytestring(obj.get_text()).rstrip('\n')
    return h

def save_image (lt_image, page_number, images_folder):
    """Try to save the image data from this LTImage object, and return the file name, if successful"""
    result = None
    if lt_image.stream:
        file_stream = lt_image.stream.get_rawdata()
        file_ext = determine_image_type(file_stream[0:4])
        if file_ext:
            file_name = ''.join([str(page_number), '_', lt_image.name, file_ext])
            if write_file(images_folder, file_name, lt_image.stream.get_rawdata(), flags='wb'):
                result = file_name
    return result

def determine_image_type (stream_first_4_bytes):
    """Find out the image file type based on the magic number comparison of the first 4 (or 2) bytes"""
    file_type = None
    bytes_as_hex = b2a_hex(stream_first_4_bytes)
    if bytes_as_hex.startswith('ffd8'):
        file_type = '.jpeg'
    elif bytes_as_hex == '89504e47':
        file_type = ',png'
    elif bytes_as_hex == '47494638':
        file_type = '.gif'
    elif bytes_as_hex.startswith('424d'):
        file_type = '.bmp'
    return file_type

def write_file (folder, filename, filedata, flags='w'):
    """Write the file data to the folder and filename combination
    (flags: 'w' for write text, 'wb' for write binary, use 'a' instead of 'w' for append)"""
    result = False
    if os.path.isdir(folder):
        try:
            file_obj = open(os.path.join(folder, filename), flags)
            file_obj.write(filedata)
            file_obj.close()
            result = True
        except IOError:
            pass
    return result


if len(sys.argv) != 2:
    print """usage:
to see the output:
\tpdf2xml file.pdf
to write output to file:
\tpdf2xml file.pdf > outfile.xml
"""
else:
    get_pages(sys.argv[1], images_folder='.')


